### ISSUE TITLE
参数询问

### ISSUE THREAD

**Issue by zhanz5** [zhmzm/Poisoning_Backdor-critical_Layers_Attack#1]
parser.add_argument('--server_lr', type=float,default=1,help="number of dataset in server using in fltrust")这个是否正确？

**Comment by zhmzm** [comment]
Hi Jenson,

This is a learning rate for server, where FLTrust sets it to extremely small. But we set all server learning rate to 1 so it is useless in our experiment.

Thanks for your report. The explanation is confusing for this parameter. I will update it.
